---
language: generic
sudo: required

services:
  - docker

env:
  - DISTRO="registry.centos.org/centos/centos:7"
  - DISTRO="registry.fedoraproject.org/fedora:latest"
  - DISTRO="registry.fedoraproject.org/fedora:rawhide"

matrix:
  allow_failures:
    - env: DISTRO="registry.fedoraproject.org/fedora:rawhide"

before_install:
  - sudo docker pull ${DISTRO}

install:
  - >
    sudo docker run --detach --volume="${PWD}":/tmp/test
    --name `sed -E -e "s,[:/\.],-,g" <<< ${DISTRO}` ${DISTRO} sleep 600
  - tests/setup_test_container.sh ${DISTRO}

script:
  - sudo docker exec `sed -E -e "s,[:/\.],-,g" <<< ${DISTRO}` bash -c 'cd /tmp/test && ./runtests.sh -v'

after_script:
  - sudo docker stop `sed -E -e "s,[:/\.],-,g" <<< ${DISTRO}`
