- name: Install RPM packages
  dnf:
    name:
      - python3-pip
      - python3-devel
    state: present

- name: install oidc_register with pip
  pip:
    name: oidc-register

# not sure of how to do this another way, but without this, oidc_register fails
- name: Get the content of the CA cert
  slurp:
    src: /etc/ipa/ca.crt
  register: ca_crt
- name: Put tinystage root CA in the list of CA's for httplib2
  blockinfile:
    block: "{{ ca_crt.content | b64decode }}"
    path: /usr/local/lib/python{{ ansible_local["python"]["py3"]["version"] }}/site-packages/httplib2/cacerts.txt

- name: register the application with oidc-register
  shell:
    cmd: oidc-register --debug --output-file {{ dest }} https://{{ ipsilon_hostname }}/idp/openidc/ {{ redirect_url }}
    creates: "{{ dest }}"
  become: yes
  become_user: vagrant
